apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumit-dev-deployment
  labels:
    app: dev-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-api
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      containers:
      - name: dev-api
        image: sumit246/dev-api:latest # Docker hub images name
        imagePullPolicy: Always  
    env:
      - name: AWS_ACCESS_KEY_ID
        value: "${AWS_ACCESS_KEY_ID}"
      - name: AWS_SECRET_ACCESS_KEY
        value: "${AWS_SECRET_ACCESS_KEY}"

---

apiVersion: v1
kind: Service
metadata:
  name: sumit-dev-services
spec:
  type: NodePort
  selector:
    app: dev-api  # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1400  # Docker-file Build Port Number

