# FROM node:14
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# ENV NODE_ENV=development
# EXPOSE 1400
# CMD ["npm", "start"]


# FROM node:18
# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm install aws-sdk dotenv
# COPY 1.sh /usr/src/app/
# RUN chmod +x /usr/src/app/1.sh
# EXPOSE 1400
# ENV AWS_REGION=us-east-1
# ENV AWS_ACCESS_KEY_ID=AKIAUDAUENSXWPCDMVPG
# ENV AWS_SECRET_ACCESS_KEY=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
# CMD ["/usr/src/app/1.sh"]


FROM node:18
RUN apt-get update && \
    apt-get install -y awscli
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN chmod +x 1.sh
RUN ./1.sh
EXPOSE 1400
ENV AWS_REGION=us-east-1
ENV AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
ENV AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
CMD ["node", "index.js"]



 
