# FROM node:14
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# ENV NODE_ENV=development
# EXPOSE 1400
# CMD ["npm", "start"]


FROM node:18
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm install aws-sdk dotenv
COPY 1.sh /usr/src/app/
RUN chmod +x /usr/src/app/start.sh
EXPOSE 1400
ENV AWS_REGION=us-east-1
CMD ["/usr/src/app/1.sh"]


 
