# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sumit-prod-deployment
#   labels:
#     app: node-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: node-api
#   template:
#     metadata:
#       labels:
#         app: node-api
#     spec:
#       containers:
#       - name: node-api
#         image: sumit246/node-api:latest  # Docker hub images name

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sumit-prod-services
# spec:
#   type: NodePort
#   selector:
#     app: node-api  # Matches the labels in the Deployment
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 1402  # Docker-file Build Port Number




apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumit-prod-deployment
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: sumit246/node-api:latest  # Docker Hub image name
        ports:
        - containerPort: 1402  # Ensure this matches the exposed port in your Dockerfile or application
        env:
          - name: NODE_ENV
            value: "Production"  # or another appropriate value
          - name: API_PORT_PROD
            valueFrom:
              secretKeyRef:
                name: sumit-prod-secret
                key: sumit-prod-port
          - name: MY_ENV_NAME_PROD
            valueFrom:
              secretKeyRef:
                name: sumit-prod-secret
                key: sumit-prod-env
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: sumit-prod-services
spec:
  type: NodePort
  selector:
    app: node-api  # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1402  # Docker-file Build Port Number
