apiVersion: v1
kind: Secret
metadata:
<<<<<<< HEAD
  name: sumit-dev-secret
type: Opaque
data:
  api-port-dev: MTQwMA==         # base64 encoded '1400'
  sumit-dev-env: RGV2ZWxvcG1lbnQ=
=======
  name: sumit-prod-secret
type: Opaque
data:
  sumit-prod-port: MTQwMg==         # base64 encoded '1402'
  sumit-prod-env: UHJvZHVjdGlvbg==  # base64 encoded 'Production'
>>>>>>> main
