apiVersion: v1
kind: Secret
metadata:
  name: aws-main-secrets
type: Opaque
data:
  aws-access-key-id: QUtJQVpHVVBKUDNMNTdFUkFFVkw=
  aws-secret-access-key: eUpUREJMa2pmUk1UczdmNHR2U3ZCK21nbFp4d2VnbS9PVldNK0dCSg==