# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sumit-stag-deployment
#   labels:
#     app: stag-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: stag-api
#   template:
#     metadata:
#       labels:
#         app: stag-api
#     spec:
#       containers:
#       - name: stag-api
#         image: sumit246/stag-api:latest  # Docker hub images name

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sumit-stag-services
# spec:
#   type: NodePort
#   selector:
#     app: stag-api  # Matches the labels in the Deployment
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 1401  # Docker-file Build Port Number




apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumit-stag-deployment
  labels:
    app: stage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage-api
  template:
    metadata:
      labels:
        app: stage-api
    spec:
      containers:
      - name: stage-api
        image: sumit246/stag-api:latest  # Ensure this tag is correct
        ports:
        - containerPort: 1401  # Ensure this matches the exposed port in your Dockerfile or application
        env:
          - name: NODE_ENV
            value: "Staging"  # or another appropriate value
          - name: API_PORT_STAGE
            valueFrom:
              secretKeyRef:
                name: stage-secret
                key: api-port-stage
          - name: MY_ENV_NAME_STAGE
            valueFrom:
              secretKeyRef:
                name: sumit-stage-secret
                key: sumit-stage-env
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sumit-stage-services
spec:
  type: NodePort
  selector:
    app: stage-api # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1401  # Docker-file Build Port Number