# # name: dev branch deployment

# # on:
# #   push:
# #     branches:
# #       - dev

# # env:
# #   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
# #   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
# #   BUILD_NUMBER: ${{ github.run_number }}

# # jobs:
# #   build-and-push:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Login to Docker Hub
# #         uses: docker/login-action@v1
# #         with:
# #           username: ${{ env.DOCKER_USERNAME }}
# #           password: ${{ env.DOCKER_PASSWORD }}

# #       - name: Set up Docker Buildx
# #         uses: docker/setup-buildx-action@v1

# #       - name: Build Docker image
# #         run: |
# #           docker build --no-cache -t dev-api:latest -f Dockerfile.dev .

# #       - name: Tag Docker image with Docker Hub username
# #         run: |
# #           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:latest

# #       - name: Push Docker image with 'latest' tag
# #         run: |
# #           docker push ${{ env.DOCKER_USERNAME }}/dev-api:latest

# #       - name: Tag Docker image with build number
# #         run: |
# #           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}
# #           docker push ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}


# #   deploy:
# #     runs-on: ubuntu-latest
# #     needs: build-and-push
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Set up AWS CLI
# #         uses: aws-actions/configure-aws-credentials@v2
# #         with:
# #           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
# #           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# #           aws-region: us-east-1

# #       - name: Install kubectl
# #         run: |
# #           curl -LO "https://dl.k8s.io/release/v1.30.3/bin/linux/amd64/kubectl"
# #           chmod +x ./kubectl
# #           sudo mv ./kubectl /usr/local/bin/kubectl
# #           kubectl version --client
      
# #       - name: Update kube config
# #         run: |
# #           mkdir -p $HOME/.kube
# #           export KUBECONFIG=$HOME/.kube/config
# #           aws eks update-kubeconfig --region us-east-1 --name ci-cd-pipeline

# #       - name: Deploy to Kubernetes
# #         run: |
# #           kubectl apply -f dev.yaml

# name: dev branch deployment

# on:
#   push:
#     branches:
#       - dev

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#   BUILD_NUMBER: ${{ github.run_number }}

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ env.DOCKER_USERNAME }}
#           password: ${{ env.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         run: |
#           docker build --no-cache -f Dockerfile.dev -t dev-api:latest .

#       - name: Tag Docker image with Docker Hub username
#         run: |
#           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:latest

#       - name: Push Docker image with 'latest' tag
#         run: |
#           docker push ${{ env.DOCKER_USERNAME }}/dev-api:latest

#       - name: Tag Docker image with build number
#         run: |
#           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}
#           docker push ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Install kubectl
#         run: |
#           curl -LO "https://dl.k8s.io/release/v1.30.3/bin/linux/amd64/kubectl"
#           chmod +x ./kubectl
#           sudo mv ./kubectl /usr/local/bin/kubectl
#           kubectl version --client
      
#       - name: Update kube config
#         run: |
#           mkdir -p $HOME/.kube
#           export KUBECONFIG=$HOME/.kube/config
#           aws eks update-kubeconfig --region us-east-1 --name ci-cd-pipeline

#       - name: Deploy to Kubernetes
#         run: |
#           ls -la
#           kubectl apply -f dev-api.yaml
#           kubectl rollout restart deployment/sumit-dev-deployment
#           kubectl rollout status deployment/sumit-dev-deployment






name: sumit branch deployment

on:
  push:
    branches:
      - sumit

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_NUMBER: ${{ github.run_number }}
  AWS_REGION: us-east-1
  SECRET_NAME: Envfile 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
 

      - name: Build Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SECRET_NAME: Envfile
        run: |
          docker build --no-cache \
            --build-arg AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_REGION=us-east-1 \
            -f Dockerfile.dev -t dev-api:latest .

      - name: Tag Docker image with Docker Hub username
        run: |
          docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:latest

      - name: Push Docker image with 'latest' tag
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/dev-api:latest

      - name: Tag Docker image with build number
        run: |
          docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.30.3/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
 
      - name: Update kube config
        run: |
          mkdir -p $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-bb-123

      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment/sumit-dev-deployment
          kubectl apply -f dev-api.yaml
          kubectl apply -f ingress.yaml





# name: main branch deployment

# on:
#   push:
#     branches:
#       - sumit

# env:
#     DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#     BUILD_NUMBER: ${{ github.run_number }}
#     AWS_REGION: us-east-1
#     SECRET_NAME_MAIN: Envfile # Replace with your actual secret name
#     AWS_DEFAULT_REGION: us-east-1
#     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ env.DOCKER_USERNAME }}
#           password: ${{ env.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         run: |
#           docker build --no-cache -f Dockerfile.dev -t dev-api:latest .

#       - name: Tag Docker image with Docker Hub username
#         run: |
#           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:latest
          
#       - name: Push Docker image with 'latest' tag
#         run: |
#            docker push ${{ env.DOCKER_USERNAME }}/dev-api:latest

#       - name: Tag Docker image with build number
#         run: |
#           docker tag dev-api:latest ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}
#           docker push ${{ env.DOCKER_USERNAME }}/dev-api:${{ env.BUILD_NUMBER }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Retrieve secrets from AWS Secrets Manager
#         run: |
#           SECRET=$(aws secretsmanager get-secret-value --secret-id ${{ env.SECRET_NAME }} --query SecretString --output text)
#           echo $SECRET > .env
#         env:
#           AWS_REGION: ${{ env.AWS_REGION }}

#       - name: Install kubectl
#         run: |
#           curl -LO "https://dl.k8s.io/release/v1.30.3/bin/linux/amd64/kubectl"
#           chmod +x ./kubectl
#           sudo mv ./kubectl /usr/local/bin/kubectl
#           kubectl version --client

      # - name: Update kube config
      #   run: |
      #     mkdir -p $HOME/.kube
      #     export KUBECONFIG=$HOME/.kube/config
      #     aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-bb-123

      # - name: Deploy to Kubernetes
      #   run: |
      #    kubectl rollout restart deployment/sumit-dev-deployment
      #    kubectl apply -f dev-api.yaml
