jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image for nest-api
        run: |
          docker-compose build nest-api

      - name: Tag Docker image for nest-api
        run: |
          docker tag sumit-api ${{ env.DOCKER_USERNAME }}/sumit-api:latest

      - name: Push Docker image for nest-api
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/sumit-api:latest

      - name: Tag Docker image with build number for nest-api
        run: |
          BUILD_NUMBER=$(date +%s)
          docker tag sumit-api ${{ env.DOCKER_USERNAME }}/sumit-api:${BUILD_NUMBER}
          docker push ${{ env.DOCKER_USERNAME }}/sumit-api:${BUILD_NUMBER}

      - name: Pull and push Redis image (optional)
        run: |
          docker pull redis:alpine


