# # name: Build and Push Docker Image

# # on:
# #   push:
# #     branches:
# #       - main

# # env:
# #   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
# #   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

# # jobs:
# #   build-and-push:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Login to Docker Hub
# #         uses: docker/login-action@v1
# #         with:
# #           username: ${{ env.DOCKER_USERNAME }}
# #           password: ${{ env.DOCKER_PASSWORD }}

# #       - name: Set up Docker Buildx
# #         uses: docker/setup-buildx-action@v1

# #       - name: Build Docker image
# #         run: docker build -t node-api:latest .

# #       - name: Tag Docker image
# #         run: docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:latest

# #       - name: Push Docker image
# #         run: docker push ${{ env.DOCKER_USERNAME }}/node-api:latest

# #       - name: Tag Docker image with build number
# #         run: |
# #           BUILD_NUMBER=$(date +%s)
# #           docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}
# #           docker push ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}



# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ env.DOCKER_USERNAME }}
#           password: ${{ env.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         run: docker build -t node-api:latest .

#       - name: Tag Docker image
#         run: docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:latest

#       - name: Push Docker image
#         run: docker push ${{ env.DOCKER_USERNAME }}/node-api:latest

#       - name: Tag Docker image with build number
#         run: |
#           BUILD_NUMBER=$(date +%s)
#           docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}
#           docker push ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}



name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

- name: Run SonarQube Scanner
    env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t node-api:latest .

      - name: Tag Docker image
        run: docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:latest

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/node-api:latest

      - name: Tag Docker image with build number
        run: |
          BUILD_NUMBER=$(date +%s)
          docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}
          docker push ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}
