# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ env.DOCKER_USERNAME }}
#           password: ${{ env.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         run: docker build -t node-api:latest .

#       - name: Tag Docker image
#         run: docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:latest

#       - name: Push Docker image
#         run: docker push ${{ env.DOCKER_USERNAME }}/node-api:latest

#       - name: Tag Docker image with build number
#         run: |
#           BUILD_NUMBER=$(date +%s)
#           docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}
#           docker push ${{ env.DOCKER_USERNAME }}/node-api:${BUILD_NUMBER}



name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t node-api:latest .

      - name: Tag Docker image
        run: docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:latest

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/node-api:latest

      - name: Get and increment build number
        id: get-build-number
        run: |
          BUILD_NUMBER=$(cat build-number.txt)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo "BUILD_NUMBER=${NEW_BUILD_NUMBER}" >> $GITHUB_ENV
          echo "${NEW_BUILD_NUMBER}" > build-number.txt

      - name: Tag Docker image with build number
        run: |
          docker tag node-api:latest ${{ env.DOCKER_USERNAME }}/node-api:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/node-api:${{ env.BUILD_NUMBER }}

      - name: Commit updated build number
        run: |
          git config --global user.name 'sumit-linearloop'
          git config --global user.email 'sumit@linearloop.io'
          git add build-number.txt
          git commit -m "Increment build number to ${{ env.BUILD_NUMBER }}"
          git push
