name: Deploy and Docker Build/Push

on:
  push:
    branches:
      - main  # Change this to your main branch or desired branch

jobs:
  deploy-and-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

      - name: Download .env file from S3
        run: |
          aws s3 cp s3://your-bucket-name/.env .env

      - name: Run shell script
        run: |
          chmod +x 1.sh
          ./1.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            sumit246/node-api:latest
            sumit246/node-api:${{ github.sha }}

      - name: Echo Build Number
        run: echo "Build Number is ${{ github.run_number }}"
